include: package:flutter_lints/flutter.yaml

analyzer: 
  # errors:
    # prefer_const_constructors: error
    # avoid_print: error
    # prefer_const_literals_to_create_immutables: error
    # always_declare_return_types: error
    # prefer_final_locals: error
    # unused_import: error
    # unused_local_variable: error
  

  
linter:
  rules:
    require_trailing_commas: true
    prefer_const_constructors: true
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_interpolation_to_compose_strings: false
    curly_braces_in_flow_control_structures: true
    avoid_multiple_declarations_per_line: true
    unawaited_futures: true

    


  

